version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:11.0.6'
    steps:
      - checkout
      - run: mvn clean package
      - store_artifacts:
          path: target/TacticsMiners.jar